# Generated by Django 5.2.8 on 2026-02-11 21:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merke', models.CharField(max_length=100)),
                ('modell', models.CharField(max_length=100)),
                ('årsmodell', models.IntegerField()),
                ('regnummer', models.CharField(max_length=10, unique=True)),
                ('kilometerstand', models.IntegerField()),
                ('drivstoff', models.CharField(max_length=50)),
                ('girkasse', models.CharField(max_length=50)),
                ('farge', models.CharField(max_length=50)),
                ('innkjøpspris', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salgspris', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('innkommet', 'Innkommet'), ('under_service', 'Under service'), ('klar_salg', 'Klar for salg'), ('solgt', 'Solgt')], default='innkommet', max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
                ('bilde', models.ImageField(blank=True, null=True, upload_to='bil_bilder/')),
                ('innkommet_dato', models.DateField(default=django.utils.timezone.now)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Biler',
                'ordering': ['-innkommet_dato'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('beskrivelse', models.TextField()),
                ('planlagt_dato', models.DateField()),
                ('estimert_kostnad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('faktisk_kostnad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fullført', models.BooleanField(default=False)),
                ('fullført_dato', models.DateField(blank=True, null=True)),
                ('ansvarlig', models.CharField(blank=True, max_length=100)),
                ('notater', models.TextField(blank=True)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('bil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicer', to='biler.bil')),
            ],
            options={
                'verbose_name_plural': 'Servicer',
                'ordering': ['-planlagt_dato'],
            },
        ),
    ]
